export default {
	GET_CURRENT_LOCATION: "GET_CURRENT_LOCATION",
	SET_NAME: "SET_NAME",
	GET_INPUT:"GET_INPUT",
	GET_ADDRESS_PREDICTIONS:"GET_ADDRESS_PREDICTIONS",
	TOGGLE_SEARCH_RESULT:"TOGGLE_SEARCH_RESULT",
	GET_SELECTED_ADDRESS:"GET_SELECTED_ADDRESS",
	GET_DISTANCE_MATRIX:"GET_DISTANCE_MATRIX",
	GET_FARE:"GET_FARE",
	BOOK_CAR:"BOOK_CAR",
	GET_NEARBY_DRIVERS:"GET_NEARBY_DRIVERS",
};   