export default {
	GET_CURRENT_LOCATION:"GET_CURRENT_LOCATION",
	GET_COMMERCE_INFORMATION:"GET_COMMERCE_INFORMATION",
	GET_COMMERCE_LOCATION:"GET_COMMERCE_LOCATION",
	GET_DISTANCE_FROM_COMMERCE:"GET_DISTANCE_FROM_COMMERCE"
};